/**
 * lang.js — Language config + full translations
 * Bahasa: Indonesia (id) | Basa Jawa (jw) | Basa Madura (md)
 */

export const LANG_KEY    = 'rajasa-lang'
export const LANGS       = ['id', 'jw', 'md']
export const LANG_LABELS = { id: 'ID', jw: 'JW', md: 'MD' }
export const LANG_NAMES  = { id: 'Indonesia', jw: 'Basa Jawa', md: 'Basa Madura' }
export const LANG_FLAGS  = { id: '🇮🇩', jw: '🏛️', md: '🏝️' }

export function getLang()       { return localStorage.getItem(LANG_KEY) || 'id' }
export function setStoredLang(l){ localStorage.setItem(LANG_KEY, l) }

/** T[lang][key] — kamus terjemahan UI */
export const T = {
  id: {
    // ── Seksi sidebar ──
    nav_overview:  'Overview',
    nav_presensi:  'Presensi',
    nav_siswa:     'Siswa',
    nav_akun:      'Akun',
    nav_manajemen: 'Manajemen',
    nav_data:      'Data',
    nav_sistem:    'Sistem',
    nav_kegiatan:  'Kegiatan',
    // ── Item menu ──
    dashboard:           'Dashboard',
    sesi_presensi:       'Sesi Presensi',
    rekap_kehadiran:     'Rekap Kehadiran',
    rekap_presensi:      'Rekap Presensi',
    kalender_akademik:   'Kalender Akademik',
    early_warning:       'Early Warning',
    logbook_pkl:         'Logbook PKL',
    e_izin:              'E-Izin',
    pusat_komunikasi:    'Pusat Komunikasi',
    gamifikasi:          'Gamifikasi',
    pengaturan_akun:     'Pengaturan Akun',
    analitik_kehadiran:  'Analitik Kehadiran',
    analitik_prestasi:   'Analitik Prestasi',
    logbook_praktik:     'Logbook Praktik',
    pengguna:            'Pengguna',
    laporan:             'Laporan',
    audit_trail:         'Audit Trail',
    pengaturan:          'Pengaturan',
    keamanan_2fa:        'Keamanan 2FA',
    // ── Tombol umum ──
    keluar:       'Keluar',
    mulai_sesi:   'Mulai Sesi Baru',

    // ── Siswa: Ringkasan Presensi (Dashboard) ──
    sc_ringkasan_judul:   'Ringkasan Presensi',
    sc_ringkasan_sub:     'Rekap kehadiran kamu di seluruh sesi laboratorium.',
    sc_tepat_waktu:       'Tepat Waktu',
    sc_terlambat:         'Terlambat',
    sc_alpha:             'Alpha',
    sc_sakit:             'Sakit',
    sc_izin:              'Izin',
    sc_gagal_muat:        'Gagal memuat data presensi.',
    sc_coba_lagi:         'Coba Lagi',

    // ── Siswa: Riwayat Presensi (Tabel) ──
    tp_judul:             'Riwayat Presensi',
    tp_subtitle:          'Rekap lengkap kehadiran kamu di seluruh sesi laboratorium.',
    tp_filter_label:      'Filter:',
    tp_filter_semua:      'Tampilkan Semua',
    tp_filter_tanggal:    'By Tanggal',
    tp_tampilkan_btn:     'Tampilkan',
    tp_tanggal_mulai:     'Tanggal mulai',
    tp_tanggal_akhir:     'Tanggal akhir',
    tp_sd:                's/d',
    tp_col_no:            'No',
    tp_col_tanggal:       'Tanggal',
    tp_col_ruangan:       'Ruangan',
    tp_col_kelas:         'Kelas',
    tp_col_jam_sesi:      'Jam Sesi',
    tp_col_selesai:       'Selesai',
    tp_col_status:        'Status',
    tp_col_keterangan:    'Keterangan',
    tp_gagal_judul:       'Gagal Memuat Data',
    tp_kosong_judul:      'Tidak Ada Data',
    tp_kosong_desc:       'Tidak ada data presensi yang sesuai dengan filter yang dipilih.',
    tp_menampilkan:       'Menampilkan',
    tp_dari:              'dari',
    tp_data:              'data',
    tp_halaman_sebelumnya:'Halaman sebelumnya',
    tp_halaman_berikutnya:'Halaman berikutnya',
    tp_halaman:           'Halaman',

    // ── Siswa: Kalender Akademik ──
    ka_judul:             'Kalender Akademik',
    ka_subtitle:          'Jadwal kegiatan akademik sekolah tahun ini.',
    ka_memuat:            'Memuat kalender akademik...',
    ka_gagal_muat:        'Gagal memuat kalender akademik.',
    ka_kosong_judul:      'Kalender Akademik Belum Tersedia',
    ka_kosong_desc:       'File kalender akademik belum diunggah oleh admin. Silakan hubungi pihak sekolah atau cek kembali nanti.',
    ka_kosong_badge:      'Menunggu unggahan dari admin',
    ka_perkecil:          'Perkecil',
    ka_perbesar:          'Perbesar',
    ka_reset:             'Reset',
    ka_download:          'Download',

    // ── Siswa: Portal E-Izin ──
    ei_judul:               'Portal E-Izin',
    ei_subtitle:            'Ajukan izin atau sakit dan pantau status persetujuannya',
    ei_ajukan_btn:          '+ Ajukan Izin',
    ei_keterangan_wajib:    'Keterangan wajib diisi.',
    ei_sukses:              'Pengajuan izin berhasil dikirim.',
    ei_form_judul:          '📝 Ajukan Izin / Sakit',
    ei_tutup:               '✕ Tutup',
    ei_jenis_label:         'Jenis',
    ei_opt_sakit:           '🏥 Sakit',
    ei_opt_izin:            '📋 Izin',
    ei_tgl_mulai:           'Tanggal Mulai',
    ei_tgl_selesai:         'Tanggal Selesai',
    ei_keterangan_label:    'Keterangan',
    ei_placeholder_alasan:  'Jelaskan alasan izin/sakit...',
    ei_batal:               'Batal',
    ei_mengirim:            'Mengirim…',
    ei_kirim_btn:           '📤 Kirim Pengajuan',
    ei_riwayat_judul:       '📋 Riwayat Izin',
    ei_refresh:             '↺ Refresh',
    ei_memuat:              'Memuat riwayat…',
    ei_kosong:              'Belum ada pengajuan izin.',
    ei_col_status:          'Status',
    ei_col_catatan:         'Catatan Guru',
    ei_status_menunggu_ortu:  '⏳ Menunggu Ortu',
    ei_status_pending:        '⏳ Menunggu Wali Kelas',
    ei_status_disetujui_wali: '🔄 Menunggu Admin',
    ei_status_ditolak_wali:   '❌ Ditolak Wali',
    ei_status_disetujui:      '✅ Disetujui',
    ei_status_ditolak:        '❌ Ditolak',
    ei_status_menunggu:       '⏳ Menunggu',

    // ── Siswa: Logbook PKL ──
    lb_status_draft:            'Draft',
    lb_status_menunggu_review:  'Menunggu Review',
    lb_status_disetujui:        'Disetujui',
    lb_status_ditolak:          'Dikembalikan',
    lb_edit_judul:              '✏️ Edit Logbook',
    lb_baru_judul:              '📝 Entri Logbook Baru',
    lb_tutup_x:                 '✕ Tutup',
    lb_tanggal_wajib:           'Tanggal wajib diisi.',
    lb_deskripsi_min:           'Deskripsi minimal 10 karakter.',
    lb_tanggal_label:           'Tanggal',
    lb_jam_mulai:                'Jam Mulai',
    lb_jam_selesai:              'Jam Selesai',
    lb_lokasi_label:             'Lokasi / Tempat PKL',
    lb_placeholder_lokasi:       'Contoh: Lab Komputer Gedung A',
    lb_deskripsi_label:          'Deskripsi Kegiatan',
    lb_placeholder_deskripsi:    'Ceritakan secara detail kegiatan yang dilakukan...',
    lb_foto_label:               'Path Foto Dokumentasi',
    lb_placeholder_foto:         'Contoh: pkl/2026/foto-hari1.jpg',
    lb_batal:                    'Batal',
    lb_simpan_draft:             '💾 Simpan Draft',
    lb_menyimpan:                'Menyimpan…',
    lb_kirim_guru:               '📤 Kirim ke Guru',
    lb_judul:                    'Logbook Praktik (PKL)',
    lb_subtitle:                 'Catat kegiatan harian PKL dan kirim ke guru pembimbing untuk divalidasi',
    lb_tambah_btn:               '+ Tambah Entri',
    lb_stat_total:               'Total',
    lb_stat_menunggu:            'Menunggu',
    lb_tab_daftar:                '📋 Daftar Logbook',
    lb_tab_penilaian:             '⭐ Penilaian Guru',
    lb_confirm_hapus:             'Yakin hapus entri ini?',
    lb_semua_status:              'Semua Status',
    lb_refresh:                   '↺ Refresh',
    lb_memuat:                    'Memuat logbook…',
    lb_kosong:                    'Belum ada entri logbook untuk bulan ini.',
    lb_col_lokasi:                'Lokasi',
    lb_col_status:                'Status',
    lb_col_catatan:               'Catatan Guru',
    lb_col_aksi:                  'Aksi',
    lb_lihat_btn:                 'Lihat',
    lb_penilaian_kosong_judul:    'Belum ada penilaian dari guru pembimbing.',
    lb_penilaian_kosong_desc:     'Penilaian akan muncul setelah guru pembimbing menilai keseluruhan logbook PKL kamu.',
    lb_penilaian_akhir_dari:      '⭐ Penilaian Akhir dari',
    lb_nilai_kedisiplinan:        'Kedisiplinan',
    lb_nilai_keterampilan:        'Keterampilan',
    lb_nilai_sikap:               'Sikap',
    lb_nilai_laporan:             'Laporan',
    lb_nilai_akhir_label:         'Nilai Akhir Logbook PKL',
    lb_catatan_dari_guru:         '💬 Catatan dari Guru Pembimbing:',
    lb_dinilai:                   'Dinilai:',
    lb_detail_judul:              '📋 Detail Logbook',
    lb_waktu_label:               'Waktu',
    lb_tutup_simple:              'Tutup',

    // ── Shared: Pusat Komunikasi ──
    ch_baru_saja:            'Baru saja',
    ch_menit_lalu:           'menit lalu',
    ch_jam_lalu:             'jam lalu',
    ch_hari_lalu:            'hari lalu',
    ch_status_open:          'Open',
    ch_status_in_progress:   'Diproses',
    ch_status_waiting:       'Menunggu',
    ch_status_resolved:      'Selesai',
    ch_status_closed:        'Ditutup',
    ch_kat_pertanyaan:       '❓ Pertanyaan',
    ch_kat_keluhan:          '😤 Keluhan',
    ch_kat_izin_khusus:      '📋 Izin Khusus',
    ch_kat_konsultasi:       '💬 Konsultasi',
    ch_kat_laporan_masalah:  '🐛 Laporan Masalah',
    ch_kat_lainnya:          '📌 Lainnya',
    ch_judul_min:            'Judul minimal 5 karakter.',
    ch_pesan_min:            'Pesan minimal 10 karakter.',
    ch_buat_tiket_judul:     '📩 Buat Tiket Baru',
    ch_judul_label:          'Judul',
    ch_placeholder_judul:    'Ringkasan singkat masalah/pertanyaan...',
    ch_kategori_label:       'Kategori',
    ch_prioritas_label:      'Prioritas',
    ch_prio_rendah:          '🔵 Rendah',
    ch_prio_normal:          '⚪ Normal',
    ch_prio_tinggi:          '🟡 Tinggi',
    ch_prio_urgent:          '🔴 Urgent',
    ch_pesan_deskripsi:      'Pesan / Deskripsi',
    ch_placeholder_pesan:    'Jelaskan pertanyaan atau masalah Anda secara detail...',
    ch_batal:                'Batal',
    ch_mengirim:             'Mengirim…',
    ch_kirim_tiket:          '📤 Kirim Tiket',
    ch_proses_btn:           '▶ Proses',
    ch_selesaikan_btn:       '✅ Selesaikan',
    ch_tutup_tiket_btn:      'Tutup Tiket',
    ch_memuat_percakapan:    'Memuat percakapan…',
    ch_belum_ada_balasan:    'Belum ada balasan. Mulai percakapan di bawah.',
    ch_catatan_internal_tag: '📌 Catatan Internal',
    ch_placeholder_balasan:  'Tulis balasan...',
    ch_catatan_internal_label: 'Catatan internal (tidak terlihat siswa)',
    ch_kirim_balasan:        '↩ Kirim',
    ch_tiket_ditutup_info:   'Tiket ini sudah ditutup. Buat tiket baru jika masih ada pertanyaan.',
    ch_judul_halaman:        'Pusat Komunikasi',
    ch_subtitle_siswa:       'Kirim pertanyaan, keluhan, atau izin khusus ke guru/admin',
    ch_subtitle_lain:        'Kelola tiket komunikasi dari siswa',
    ch_buat_tiket_short:     '+ Buat Tiket',
    ch_cari_placeholder:     '🔍 Cari judul tiket...',
    ch_semua_status:         'Semua Status',
    ch_semua_kategori:       'Semua Kategori',
    ch_refresh:              '↺ Refresh',
    ch_memuat_tiket:         'Memuat tiket…',
    ch_kosong_filter:        'Tidak ada tiket yang cocok dengan filter ini.',
    ch_kosong_siswa:         'Belum ada tiket. Klik "+ Buat Tiket" untuk memulai.',
    ch_kosong_lain:          'Tidak ada tiket masuk saat ini.',
    ch_balasan_suffix:       'balasan',
    ch_hapus_tiket_title:    'Hapus tiket',
    ch_confirm_hapus:        'Yakin hapus tiket ini?',

    // ── Shared: Gamifikasi ──
    gm_tipe_hadir_tepat:      'Hadir Tepat Waktu',
    gm_tipe_hadir_terlambat:  'Hadir (Terlambat)',
    gm_tipe_izin_surat:       'Izin dengan Surat',
    gm_tipe_streak7:          'Bonus Streak 7 Hari',
    gm_tipe_streak30:         'Bonus Streak 30 Hari',
    gm_tipe_perfect_month:    'Bonus Perfect Month',
    gm_tipe_submit_logbook:   'Submit Logbook',
    gm_tipe_logbook_approved: 'Logbook Disetujui',
    gm_tipe_tiket_selesai:    'Tiket Diselesaikan',
    gm_tipe_early_bird:       'Early Bird',
    gm_tipe_bonus_admin:      'Bonus dari Admin',
    gm_memuat_profil:         'Memuat profil gamifikasi…',
    gm_data_kosong:           'Data tidak tersedia.',
    gm_siswa_aktif:           'Siswa Aktif',
    gm_total_poin_bulan:      'Total Poin Bulan Ini',
    gm_badge_diraih:          'Badge Diraih',
    gm_top5_judul:            '🏆 Top 5 Siswa Bulan Ini',
    gm_belum_ada_poin:        'Belum ada data poin. Jalankan kalkulasi poin terlebih dahulu.',
    gm_col_siswa:             'Siswa',
    gm_col_rombel:            'Rombel',
    gm_col_poin:              'Poin',
    gm_hint_cari_siswa:       '💡 Untuk lihat profil poin siswa tertentu, masukkan siswa_id di kolom pencarian di atas.',
    gm_total_poin:            'Total Poin',
    gm_poin_lagi_ke:          'poin lagi ke',
    gm_poin_bulan_ini:        'Poin Bulan Ini',
    gm_ranking_rombel:        'Ranking Rombel',
    gm_streak_hari_ini:       'Streak Hari Ini',
    gm_badge_diraih_section:  '🎖️ Badge Diraih',
    gm_riwayat_poin_judul:    '📋 Riwayat Poin Terbaru',
    gm_belum_ada_riwayat:     'Belum ada riwayat poin.',
    gm_col_aktivitas:         'Aktivitas',
    gm_global_semua_rombel:   '🌐 Global (semua rombel)',
    gm_refresh:               '↺ Refresh',
    gm_poin_suffix:           'poin',
    gm_memuat_leaderboard:    'Memuat leaderboard…',
    gm_belum_ada_poin_periode:'Belum ada data poin untuk periode ini.',
    gm_col_hari_hadir:        'Hari Hadir',
    gm_kamu_suffix:           '← Kamu',
    gm_posisi_kamu:           '📍 Posisi kamu bulan ini:',
    gm_kat_kehadiran:         '📅 Kehadiran',
    gm_kat_logbook:           '📒 Logbook PKL',
    gm_kat_komunikasi:        '💬 Komunikasi',
    gm_kat_prestasi:          '🏆 Prestasi',
    gm_kat_khusus:            '⭐ Khusus',
    gm_memuat_katalog:        'Memuat katalog badge…',
    gm_diraih_tag:            '✅ Diraih',
    gm_confirm_hitung_prefix: 'Hitung ulang poin & badge untuk bulan',
    gm_confirm_hitung_suffix: '? Proses ini akan memperbarui semua data poin bulan tersebut.',
    gm_kalkulasi_judul:       '⚙️ Kalkulasi Poin & Badge',
    gm_kalkulasi_desc:        'Jalankan kalkulasi ulang poin dan badge untuk semua siswa aktif dalam satu bulan. Biasanya dijalankan di akhir bulan atau setelah data presensi dikoreksi.',
    gm_menghitung:            '⏳ Menghitung…',
    gm_hitung_sekarang:       '▶ Hitung Sekarang',
    gm_hasil_selesai:         '✅ Selesai —',
    gm_hasil_siswa_diproses:  'siswa diproses ·',
    gm_hasil_poin_diberikan:  'poin diberikan ·',
    gm_hasil_badge_diraih:    'badge diraih',
    gm_tab_profil:            '🎮 Profil Poin',
    gm_tab_leaderboard:       '🏆 Leaderboard',
    gm_tab_katalog:           '🎖️ Katalog Badge',
    gm_judul_halaman:         'Gamifikasi Kehadiran',
    gm_subtitle:              'Kumpulkan poin, raih badge, dan kompetisi di leaderboard bersama teman sekelasmu',
    gm_placeholder_siswa_id:  'Masukkan siswa_id untuk lihat profil siswa...',
    gm_kosongkan_global:      'Kosongkan untuk lihat statistik global',

    // ── Guru: Dashboard & Halaman ──
    gu_memuat:                'Memuat…',
    gu_memuat_dashboard:      'Memuat dashboard…',
    gu_sesi_berjalan:         'Sesi Presensi Sedang Berjalan',
    gu_dimulai:               'Dimulai',
    gu_siswa_scan:            'siswa scan',
    gu_kelola_sesi:           'Kelola Sesi',
    gu_tidak_ada_sesi:        'Tidak ada sesi aktif.',
    gu_mulai_sesi_baru:       '▶ Mulai Sesi Baru',
    gu_early_warning_judul:   '⚠️ Early Warning',
    gu_lihat_semua:           'Lihat semua →',
    gu_tidak_ada_alpha:       '✅ Tidak ada siswa alpha tinggi',
    gu_alpha_suffix:          '× alpha',
    gu_logbook_pending_judul: '📒 Logbook Pending',
    gu_tidak_ada_logbook_pend:'✅ Tidak ada logbook pending',
    gu_kontrol_sesi:          '▶ Kontrol Sesi',
    gu_status_aktif:          'Berjalan',
    gu_status_paused:         'Dijeda',
    gu_status_selesai:        'Selesai',
    gu_total_scan:            'Total Scan',
    gu_jeda:                  '⏸ Jeda',
    gu_lanjutkan:             '▶ Lanjutkan',
    gu_selesaikan:            '⏹ Selesaikan',
    gu_mode_presensi:         'Mode Presensi',
    gu_mode_rombel:           'Rombel (kelas reguler)',
    gu_mode_piket:            'Piket (siswa terlambat)',
    gu_pilih_rombel:          '-- Pilih Rombel --',
    gu_jam_label:             'Jam Pelajaran (pilih max 3 jam berurutan)',
    gu_jam_prefix:            'Jam',
    gu_memulai:               'Memulai…',
    gu_mulai_sesi_btn:        '✅ Mulai Sesi',
    gu_batal:                 'Batal',
    gu_pilih_jam_error:       'Pilih setidaknya 1 jam pelajaran.',
    gu_pilih_rombel_error:    'Pilih rombel terlebih dahulu.',
    gu_log_scan_judul:        '📡 Log Scan Terbaru',
    gu_belum_ada_scan:        'Belum ada scan.',
    gu_col_jam_scan:          'Jam Scan',
    gu_semua_rombel:          'Semua Rombel',
    gu_semua_status:          'Semua Status',
    gu_semua:                 'Semua',
    gu_tidak_ada_data:        'Tidak ada data.',
    gu_col_nama_siswa:        'Nama Siswa',
    gu_col_nis:               'NIS',
    gu_periode_label:         'Periode:',
    gu_hari_suffix:           'hari',
    gu_min_alpha:             'Min Alpha:',
    gu_tidak_ada_alpha_high:  '✅ Tidak ada siswa alpha tinggi.',
    gu_col_tingkat:           'Tingkat',
    gu_col_alpha:             'Alpha',
    gu_col_rate_hadir:        'Rate Hadir',
    gu_review_label:          'Review Logbook',
    gu_catatan_placeholder:   'Catatan (wajib jika dikembalikan)...',
    gu_catatan_wajib:         'Catatan wajib diisi saat mengembalikan.',
    gu_setujui:               '✅ Setujui',
    gu_kembalikan:            '↩ Kembalikan',
    gu_col_deskripsi:         'Deskripsi',
    gu_tidak_ada_izin_pend:   '✅ Tidak ada izin pending.',
    gu_confirm_approve:       'Setujui izin ini?',
    gu_confirm_reject:        'Tolak izin ini?',
    gu_akun_judul:            '⚙️ Pengaturan Akun',
    gu_nama_label:            'Nama',
    gu_username_label:        'Username',
    gu_email_label:           'Email',
    gu_role_label:            'Role',
    gu_ganti_password:        'Ganti Password',
    gu_password_wajib:        'Password wajib diisi.',
    gu_password_min:          'Minimal 6 karakter.',
    gu_password_tidak_cocok:  'Konfirmasi tidak cocok.',
    gu_password_baru_label:   'Password Baru',
    gu_konfirmasi_label:      'Konfirmasi',
    gu_placeholder_password:  'Minimal 6 karakter',
    gu_placeholder_konfirmasi:'Ulangi password',
    gu_menyimpan:             'Menyimpan…',
    gu_simpan_password:       '💾 Simpan Password',
    gu_password_sukses:       'Password berhasil diperbarui.',

    // ── Admin: Dashboard ──
    ad_dashboard_judul:       'Dashboard Administrator',
    ad_ringkasan:             'Ringkasan sistem presensi',
    ad_memuat_dashboard:      'Memuat data dashboard...',
    ad_gagal_memuat:          'Gagal Memuat Dashboard',
    ad_gagal_memuat_msg:      'Gagal memuat dashboard.',
    ad_tidak_ada_rombel:      'Tidak ada data rombel.',
    ad_tidak_ada_sesi_aktif:  'Tidak ada sesi aktif',
    ad_sesi_semua_selesai:    'Semua sesi presensi sudah selesai.',
    ad_col_mode:              'Mode',
    ad_status_aktif:          'Aktif',
    ad_status_paused:         'Paused',
    ad_qa_sesi_label:         'Lihat Sesi Aktif',
    ad_qa_sesi_desc:          'Monitor sesi berlangsung',
    ad_qa_users_label:        'Kelola Pengguna',
    ad_qa_users_desc:         'Tambah/edit akun',
    ad_qa_laporan_label:      'Buat Laporan',
    ad_qa_laporan_desc:       'Export PDF/Excel',
    ad_qa_izin_label:         'Review E-Izin',
    ad_qa_izin_desc:          'Approval izin siswa',
    ad_tren_judul:            'Tren Kehadiran (14 Hari Terakhir)',
    ad_refresh:               '↻ Refresh',
    ad_belum_ada_tren:        'Belum ada data tren.',
    ad_distribusi_status:     'Distribusi Status',
    ad_kehadiran_rombel:      'Kehadiran per Rombel',
    ad_aksi_cepat:            'Aksi Cepat',
    ad_sesi_aktif_sekarang:   'Sesi Aktif Sekarang',
    ad_stat_siswa_aktif:      'Total Siswa Aktif',
    ad_stat_total_rombel:     'Total Rombel',
    ad_stat_sesi_aktif:       'Sesi Presensi Aktif',
    ad_stat_tingkat_hadir:    'Tingkat Kehadiran',
    ad_stat_aktif_terdaftar:  'Aktif terdaftar',
    ad_stat_kelas_aktif:      'Kelas aktif',
    ad_stat_berlangsung:      'Berlangsung',
    ad_stat_tidak_ada_sesi:   'Tidak ada sesi',
    ad_stat_baik:             'Baik',
    ad_stat_cukup:            'Cukup',
    ad_stat_perlu_perhatian:  'Perlu perhatian',

    // ── Admin: Sesi ──
    ad_sesi_akhiri:           'Akhiri Paksa',
    ad_memproses:             'Memproses…',
    ad_sesi_diakhiri:         'Sesi berhasil diakhiri.',
    ad_sesi_berjalan:         'Sedang Berjalan',
    ad_sesi_dijeda:           'Dijeda',
    ad_sesi_expired:          'Expired',
    ad_sesi_bermasalah:       'Bermasalah',
    ad_sesi_terputus:         'Terputus',
    ad_sesi_selesai:          'Selesai',
    ad_sesi_gagal:            'Gagal',
    ad_total_sesi:            'Total Sesi',
    ad_sesi_coba_tgl_lain:    'Coba pilih tanggal lain.',
    ad_sesi_auto_muncul:      'Data akan muncul otomatis saat guru membuka sesi presensi.',
    ad_sesi_belum_ada:        'Belum ada sesi hari ini',
    ad_sesi_tidak_ada:        'Tidak ada sesi pada tanggal ini',
    ad_kurang_1_mnt:          '< 1 mnt',

    // ── Admin: Early Warning ──
    ad_kritis:                'Kritis',
    ad_tinggi:                'Tinggi',
    ad_sedang:                'Sedang',
    ad_notif_wali:            'Notifikasi Wali Kelas',
    ad_mengirim:              'Mengirim…',
    ad_notif_sukses:          'Notifikasi berhasil dikirim.',
    ad_hadir_baik:            'Kehadiran dalam kondisi baik!',
    ad_tidak_ada_hasil:       'Tidak ada hasil yang sesuai filter',
    ad_coba_ubah_filter:      'Coba ubah filter level atau kata kunci pencarian.',

    // ── Admin: Audit ──
    ad_aktivitas_hari_ini:    'Aktivitas Hari Ini',
    ad_login_hari_ini:        'Login Hari Ini',
    ad_total_log:             'Total Log',
    ad_pengguna_aktif:        'Pengguna Aktif',
    ad_pengguna_terlibat:     'Pengguna Terlibat',
    ad_modul_berbeda:         'Modul Berbeda',
    ad_sedang_online:         'Sedang Online',
    ad_hari_ini:              'Hari ini',
    ad_7_hari:                '7 hari',
    ad_30_hari:               '30 hari',
    ad_tidak_ada_data:        'Tidak ada data',
    ad_mobile:                'Mobile',
    ad_tablet:                'Tablet',

    // ── Admin: Laporan ──
    ad_per_hari:              'Per Hari',
    ad_per_rombel:            'Per Rombel',
    ad_per_siswa:             'Per Siswa',
    ad_col_nisn:              'NISN',
    ad_col_nama:              'Nama',
    ad_col_tingkatan:         'Tingkatan',
    ad_col_rate:              'Rate (%)',
    ad_col_rate_hadir:        'Rate Kehadiran',
    ad_export_gagal:          'Export gagal. Coba lagi.',
    ad_bulan_ini:             'Bulan ini',
    ad_bulan_lalu:            'Bulan lalu',

    // ── Admin: Users ──
    ad_buat_pengguna:         'Buat Pengguna',
    ad_akun_guru_sukses:      'Akun guru berhasil dibuat.',
    ad_akun_siswa_sukses:     'Akun siswa berhasil dibuat.',
    ad_hapus:                 'Hapus',
    ad_konfirmasi:            'Konfirmasi',
    ad_menyimpan:             'Menyimpan…',
    ad_memuat:                'Memuat…',
    ad_password_reset_sukses: 'Password berhasil direset.',
    ad_pengguna_dihapus:      'Pengguna berhasil dihapus.',
    ad_pengguna_diperbarui:   'Pengguna berhasil diperbarui.',
    ad_reset_password:        'Reset Password',
    ad_simpan_perubahan:      'Simpan Perubahan',
    ad_online:                'Online',
    ad_idle:                  'Idle',
    ad_offline:               'Offline',
    ad_aktif:                 'Aktif',
    ad_nonaktif:              'Nonaktif',
    ad_role_admin:            'Admin',
    ad_role_guru:             'Guru',
    ad_role_siswa:            'Siswa',
    ad_role_staff:            'Staff',
    ad_role_intern:           'Intern',

    // ── Admin: E-Izin ──
    ad_dispensasi:            'Dispensasi',
    ad_mengirim_izin:         'Mengirim...',
    ad_menyimpan_izin:        'Menyimpan...',
    ad_pengajuan_sukses:      'Pengajuan berhasil dikirim! Menunggu persetujuan wali kelas.',
    ad_catatan_opsional:      '(opsional)',
    ad_catatan_wajib_tolak:   '(wajib diisi saat menolak)',

    // ── Admin: Logbook ──
    ad_belum_ada_penilaian2:  'Belum ada penilaian yang diberikan.',
    ad_catatan_wajib_logbook: 'Catatan wajib diisi saat mengembalikan logbook.',

    // ── Admin: Analitik Prestasi & Pengaturan ──
    ad_nis_wajib:             'NIS siswa wajib diisi.',
    ad_mapel_wajib:           'Mata pelajaran wajib dipilih.',
    ad_tahun_ajaran_wajib:    'Tahun ajaran wajib dipilih.',
    ad_nilai_harian:          'Nilai Harian (40%)',
    ad_nilai_uts:             'Nilai UTS (30%)',
    ad_nilai_uas:             'Nilai UAS (30%)',
    ad_rata_rata_nilai:       'Rata-rata Nilai',
    ad_rate_hadir_pct:        'Rate Kehadiran (%)',
    ad_nilai_akhir:           'Nilai Akhir',
    ad_dalam_pengembangan:    '🚧 Dalam pengembangan',
    ad_simpan:                'Simpan',
    ad_tambah:                'Tambah',
    ad_edit:                  'Edit',
    ad_berhasil_disimpan:     'Berhasil disimpan.',
    ad_berhasil_dihapus:      'Berhasil dihapus.',
    ad_konfirmasi_hapus:      'Yakin hapus ini?',
  },

  jw: {
    nav_overview:  'Ringkesan',
    nav_presensi:  'Presensi',
    nav_siswa:     'Murid',
    nav_akun:      'Akun',
    nav_manajemen: 'Manajemen',
    nav_data:      'Data',
    nav_sistem:    'Sistem',
    nav_kegiatan:  'Kagiyatan',
    dashboard:           'Dasbor',
    sesi_presensi:       'Sesi Presensi',
    rekap_kehadiran:     'Rekap Rawuh',
    rekap_presensi:      'Rekap Rawuh',
    kalender_akademik:   'Almanak Akademik',
    early_warning:       'Tandha Waspada',
    logbook_pkl:         'Catetan PKL',
    e_izin:              'E-Ijin',
    pusat_komunikasi:    'Pusat Komunikasi',
    gamifikasi:          'Gamifikasi',
    pengaturan_akun:     'Setelan Akun',
    analitik_kehadiran:  'Analitik Rawuh',
    analitik_prestasi:   'Analitik Prestasi',
    logbook_praktik:     'Catetan Praktik',
    pengguna:            'Pengguna',
    laporan:             'Laporan',
    audit_trail:         'Audit Trail',
    pengaturan:          'Setelan',
    keamanan_2fa:        'Keamanan 2FA',
    keluar:       'Metu',
    mulai_sesi:   'Miwiti Sesi',

    // ── Siswa: Ringkasan Presensi (Dashboard) ──
    sc_ringkasan_judul:   'Ringkesan Presensi',
    sc_ringkasan_sub:     'Rekap rawuhmu ing kabeh sesi laboratorium.',
    sc_tepat_waktu:       'Tepat Wektu',
    sc_terlambat:         'Telat',
    sc_alpha:             'Alpha',
    sc_sakit:             'Lara',
    sc_izin:              'Ijin',
    sc_gagal_muat:        'Gagal mbukak data presensi.',
    sc_coba_lagi:         'Coba Maneh',

    // ── Siswa: Riwayat Presensi (Tabel) ──
    tp_judul:             'Riwayat Presensi',
    tp_subtitle:          'Rekap lengkap rawuhmu ing kabeh sesi laboratorium.',
    tp_filter_label:      'Filter:',
    tp_filter_semua:      'Tampilake Kabeh',
    tp_filter_tanggal:    'Miturut Tanggal',
    tp_tampilkan_btn:     'Tampilake',
    tp_tanggal_mulai:     'Tanggal wiwitan',
    tp_tanggal_akhir:     'Tanggal pungkasan',
    tp_sd:                's/d',
    tp_col_no:            'No',
    tp_col_tanggal:       'Tanggal',
    tp_col_ruangan:       'Ruangan',
    tp_col_kelas:         'Kelas',
    tp_col_jam_sesi:      'Jam Sesi',
    tp_col_selesai:       'Rampung',
    tp_col_status:        'Status',
    tp_col_keterangan:    'Katrangan',
    tp_gagal_judul:       'Gagal Mbukak Data',
    tp_kosong_judul:      'Ora Ana Data',
    tp_kosong_desc:       'Ora ana data presensi sing cocog karo filter sing dipilih.',
    tp_menampilkan:       'Nampilake',
    tp_dari:              'saka',
    tp_data:              'data',
    tp_halaman_sebelumnya:'Kaca sadurunge',
    tp_halaman_berikutnya:'Kaca sabanjure',
    tp_halaman:           'Kaca',

    // ── Siswa: Kalender Akademik ──
    ka_judul:             'Kalender Akademik',
    ka_subtitle:          'Jadwal kagiyatan akademik sekolah taun iki.',
    ka_memuat:            'Mbukak kalender akademik...',
    ka_gagal_muat:        'Gagal mbukak kalender akademik.',
    ka_kosong_judul:      'Kalender Akademik Durung Ana',
    ka_kosong_desc:       'File kalender akademik durung diunggah dening admin. Mangga hubungi pihak sekolah utawa cek maneh sesuk.',
    ka_kosong_badge:      'Ngenteni unggahan saka admin',
    ka_perkecil:          'Cilikake',
    ka_perbesar:          'Gedhekake',
    ka_reset:             'Reset',
    ka_download:          'Undhuh',

    // ── Siswa: Portal E-Izin ──
    ei_judul:               'Portal E-Ijin',
    ei_subtitle:            'Ajokaké ijin utawa lara lan pantau status persetujuané',
    ei_ajukan_btn:          '+ Ajokaké Ijin',
    ei_keterangan_wajib:    'Katrangan kudu diisi.',
    ei_sukses:              'Pengajuan ijin kasil dikirim.',
    ei_form_judul:          '📝 Ajokaké Ijin / Lara',
    ei_tutup:               '✕ Tutup',
    ei_jenis_label:         'Jinis',
    ei_opt_sakit:           '🏥 Lara',
    ei_opt_izin:            '📋 Ijin',
    ei_tgl_mulai:           'Tanggal Wiwitan',
    ei_tgl_selesai:         'Tanggal Rampung',
    ei_keterangan_label:    'Katrangan',
    ei_placeholder_alasan:  'Jelasaké alasan ijin/lara...',
    ei_batal:               'Batal',
    ei_mengirim:            'Ngirim…',
    ei_kirim_btn:           '📤 Kirim Pengajuan',
    ei_riwayat_judul:       '📋 Riwayat Ijin',
    ei_refresh:             '↺ Refresh',
    ei_memuat:              'Mbukak riwayat…',
    ei_kosong:              'Durung ana pengajuan ijin.',
    ei_col_status:          'Status',
    ei_col_catatan:         'Katrangan Guru',
    ei_status_menunggu_ortu:  '⏳ Ngenteni Wong Tuwa',
    ei_status_pending:        '⏳ Ngenteni Wali Kelas',
    ei_status_disetujui_wali: '🔄 Ngenteni Admin',
    ei_status_ditolak_wali:   '❌ Ditolak Wali',
    ei_status_disetujui:      '✅ Disetujui',
    ei_status_ditolak:        '❌ Ditolak',
    ei_status_menunggu:       '⏳ Ngenteni',

    // ── Siswa: Logbook PKL ──
    lb_status_draft:            'Draft',
    lb_status_menunggu_review:  'Ngenteni Review',
    lb_status_disetujui:        'Disetujui',
    lb_status_ditolak:          'Dibalèkaké',
    lb_edit_judul:              '✏️ Edit Logbook',
    lb_baru_judul:              '📝 Entri Logbook Anyar',
    lb_tutup_x:                 '✕ Tutup',
    lb_tanggal_wajib:           'Tanggal kudu diisi.',
    lb_deskripsi_min:           'Deskripsi minimal 10 aksara.',
    lb_tanggal_label:           'Tanggal',
    lb_jam_mulai:                'Jam Wiwitan',
    lb_jam_selesai:              'Jam Rampung',
    lb_lokasi_label:             'Lokasi / Panggonan PKL',
    lb_placeholder_lokasi:       'Conto: Lab Komputer Gedung A',
    lb_deskripsi_label:          'Deskripsi Kagiyatan',
    lb_placeholder_deskripsi:    'Critakaké kanthi detail kagiyatan sing ditindakaké...',
    lb_foto_label:               'Path Foto Dokumentasi',
    lb_placeholder_foto:         'Conto: pkl/2026/foto-dina1.jpg',
    lb_batal:                    'Batal',
    lb_simpan_draft:             '💾 Simpen Draft',
    lb_menyimpan:                'Nyimpen…',
    lb_kirim_guru:               '📤 Kirim menyang Guru',
    lb_judul:                    'Logbook Praktik (PKL)',
    lb_subtitle:                 'Nyatet kagiyatan saben dina PKL lan kirim menyang guru pembimbing kanggo divalidasi',
    lb_tambah_btn:               '+ Tambah Entri',
    lb_stat_total:               'Total',
    lb_stat_menunggu:            'Ngenteni',
    lb_tab_daftar:                '📋 Daftar Logbook',
    lb_tab_penilaian:             '⭐ Penilaian Guru',
    lb_confirm_hapus:             'Yakin mbusak entri iki?',
    lb_semua_status:              'Kabeh Status',
    lb_refresh:                   '↺ Refresh',
    lb_memuat:                    'Mbukak logbook…',
    lb_kosong:                    'Durung ana entri logbook kanggo sasi iki.',
    lb_col_lokasi:                'Lokasi',
    lb_col_status:                'Status',
    lb_col_catatan:               'Katrangan Guru',
    lb_col_aksi:                  'Aksi',
    lb_lihat_btn:                 'Deleng',
    lb_penilaian_kosong_judul:    'Durung ana penilaian saka guru pembimbing.',
    lb_penilaian_kosong_desc:     'Penilaian bakal muncul sawise guru pembimbing nilai kabeh logbook PKL-mu.',
    lb_penilaian_akhir_dari:      '⭐ Penilaian Pungkasan saka',
    lb_nilai_kedisiplinan:        'Kedisiplinan',
    lb_nilai_keterampilan:        'Katrampilan',
    lb_nilai_sikap:               'Sikap',
    lb_nilai_laporan:             'Laporan',
    lb_nilai_akhir_label:         'Nilai Pungkasan Logbook PKL',
    lb_catatan_dari_guru:         '💬 Katrangan saka Guru Pembimbing:',
    lb_dinilai:                   'Dinilai:',
    lb_detail_judul:              '📋 Detail Logbook',
    lb_waktu_label:               'Wektu',
    lb_tutup_simple:              'Tutup',

    // ── Shared: Pusat Komunikasi ──
    ch_baru_saja:            'Lagi wae',
    ch_menit_lalu:           'menit kepungkur',
    ch_jam_lalu:             'jam kepungkur',
    ch_hari_lalu:            'dina kepungkur',
    ch_status_open:          'Open',
    ch_status_in_progress:   'Diproses',
    ch_status_waiting:       'Ngenteni',
    ch_status_resolved:      'Rampung',
    ch_status_closed:        'Ditutup',
    ch_kat_pertanyaan:       '❓ Pitakonan',
    ch_kat_keluhan:          '😤 Sesambat',
    ch_kat_izin_khusus:      '📋 Ijin Khusus',
    ch_kat_konsultasi:       '💬 Konsultasi',
    ch_kat_laporan_masalah:  '🐛 Laporan Masalah',
    ch_kat_lainnya:          '📌 Liyane',
    ch_judul_min:            'Judul minimal 5 aksara.',
    ch_pesan_min:            'Pesen minimal 10 aksara.',
    ch_buat_tiket_judul:     '📩 Gawe Tiket Anyar',
    ch_judul_label:          'Judul',
    ch_placeholder_judul:    'Ringkesan cendhak masalah/pitakonan...',
    ch_kategori_label:       'Kategori',
    ch_prioritas_label:      'Prioritas',
    ch_prio_rendah:          '🔵 Sithik',
    ch_prio_normal:          '⚪ Normal',
    ch_prio_tinggi:          '🟡 Dhuwur',
    ch_prio_urgent:          '🔴 Urgent',
    ch_pesan_deskripsi:      'Pesen / Deskripsi',
    ch_placeholder_pesan:    'Jelasaké pitakonan utawa masalah panjenengan kanthi detail...',
    ch_batal:                'Batal',
    ch_mengirim:             'Ngirim…',
    ch_kirim_tiket:          '📤 Kirim Tiket',
    ch_proses_btn:           '▶ Proses',
    ch_selesaikan_btn:       '✅ Rampungaké',
    ch_tutup_tiket_btn:      'Tutup Tiket',
    ch_memuat_percakapan:    'Mbukak omong-omongan…',
    ch_belum_ada_balasan:    'Durung ana wangsulan. Wiwiti omong-omongan ing ngisor iki.',
    ch_catatan_internal_tag: '📌 Katrangan Internal',
    ch_placeholder_balasan:  'Tulis wangsulan...',
    ch_catatan_internal_label: 'Katrangan internal (ora katon murid)',
    ch_kirim_balasan:        '↩ Kirim',
    ch_tiket_ditutup_info:   'Tiket iki wis ditutup. Gawe tiket anyar yen isih ana pitakonan.',
    ch_judul_halaman:        'Pusat Komunikasi',
    ch_subtitle_siswa:       'Kirim pitakonan, sesambat, utawa ijin khusus menyang guru/admin',
    ch_subtitle_lain:        'Kelola tiket komunikasi saka murid',
    ch_buat_tiket_short:     '+ Gawe Tiket',
    ch_cari_placeholder:     '🔍 Golèk judul tiket...',
    ch_semua_status:         'Kabeh Status',
    ch_semua_kategori:       'Kabeh Kategori',
    ch_refresh:              '↺ Refresh',
    ch_memuat_tiket:         'Mbukak tiket…',
    ch_kosong_filter:        'Ora ana tiket sing cocog karo filter iki.',
    ch_kosong_siswa:         'Durung ana tiket. Klik "+ Gawe Tiket" kanggo miwiti.',
    ch_kosong_lain:          'Ora ana tiket mlebu saiki.',
    ch_balasan_suffix:       'wangsulan',
    ch_hapus_tiket_title:    'Busak tiket',
    ch_confirm_hapus:        'Yakin mbusak tiket iki?',

    // ── Shared: Gamifikasi ──
    gm_tipe_hadir_tepat:      'Rawuh Tepat Wektu',
    gm_tipe_hadir_terlambat:  'Rawuh (Telat)',
    gm_tipe_izin_surat:       'Ijin nganggo Surat',
    gm_tipe_streak7:          'Bonus Streak 7 Dina',
    gm_tipe_streak30:         'Bonus Streak 30 Dina',
    gm_tipe_perfect_month:    'Bonus Perfect Month',
    gm_tipe_submit_logbook:   'Submit Logbook',
    gm_tipe_logbook_approved: 'Logbook Disetujui',
    gm_tipe_tiket_selesai:    'Tiket Dirampungaké',
    gm_tipe_early_bird:       'Early Bird',
    gm_tipe_bonus_admin:      'Bonus saka Admin',
    gm_memuat_profil:         'Mbukak profil gamifikasi…',
    gm_data_kosong:           'Data ora ana.',
    gm_siswa_aktif:           'Murid Aktif',
    gm_total_poin_bulan:      'Total Poin Sasi Iki',
    gm_badge_diraih:          'Badge Diraih',
    gm_top5_judul:            '🏆 Top 5 Murid Sasi Iki',
    gm_belum_ada_poin:        'Durung ana data poin. Mlaku kalkulasi poin dhisik.',
    gm_col_siswa:             'Murid',
    gm_col_rombel:            'Rombel',
    gm_col_poin:              'Poin',
    gm_hint_cari_siswa:       '💡 Kanggo ndeleng profil poin murid tartamtu, lebokna siswa_id ing kolom panggolèkan ing dhuwur.',
    gm_total_poin:            'Total Poin',
    gm_poin_lagi_ke:          'poin maneh menyang',
    gm_poin_bulan_ini:        'Poin Sasi Iki',
    gm_ranking_rombel:        'Ranking Rombel',
    gm_streak_hari_ini:       'Streak Dina Iki',
    gm_badge_diraih_section:  '🎖️ Badge Diraih',
    gm_riwayat_poin_judul:    '📋 Riwayat Poin Anyar',
    gm_belum_ada_riwayat:     'Durung ana riwayat poin.',
    gm_col_aktivitas:         'Aktivitas',
    gm_global_semua_rombel:   '🌐 Global (kabeh rombel)',
    gm_refresh:               '↺ Refresh',
    gm_poin_suffix:           'poin',
    gm_memuat_leaderboard:    'Mbukak leaderboard…',
    gm_belum_ada_poin_periode:'Durung ana data poin kanggo periode iki.',
    gm_col_hari_hadir:        'Dina Rawuh',
    gm_kamu_suffix:           '← Kowe',
    gm_posisi_kamu:           '📍 Posisi kowe sasi iki:',
    gm_kat_kehadiran:         '📅 Rawuh',
    gm_kat_logbook:           '📒 Logbook PKL',
    gm_kat_komunikasi:        '💬 Komunikasi',
    gm_kat_prestasi:          '🏆 Prestasi',
    gm_kat_khusus:            '⭐ Khusus',
    gm_memuat_katalog:        'Mbukak katalog badge…',
    gm_diraih_tag:            '✅ Diraih',
    gm_confirm_hitung_prefix: 'Etung maneh poin & badge kanggo sasi',
    gm_confirm_hitung_suffix: '? Proses iki bakal ngapdet kabeh data poin sasi kasebut.',
    gm_kalkulasi_judul:       '⚙️ Kalkulasi Poin & Badge',
    gm_kalkulasi_desc:        'Mlaku kalkulasi ulang poin lan badge kanggo kabeh murid aktif ing sasi. Biasane ditindakaké ing pungkasan sasi utawa sawise data presensi dikoreksi.',
    gm_menghitung:            '⏳ Ngitung…',
    gm_hitung_sekarang:       '▶ Etung Saiki',
    gm_hasil_selesai:         '✅ Rampung —',
    gm_hasil_siswa_diproses:  'murid diproses ·',
    gm_hasil_poin_diberikan:  'poin diwenehaké ·',
    gm_hasil_badge_diraih:    'badge diraih',
    gm_tab_profil:            '🎮 Profil Poin',
    gm_tab_leaderboard:       '🏆 Leaderboard',
    gm_tab_katalog:           '🎖️ Katalog Badge',
    gm_judul_halaman:         'Gamifikasi Rawuh',
    gm_subtitle:              'Kumpulaké poin, raih badge, lan kompetisi ing leaderboard karo kanca sakelasmu',
    gm_placeholder_siswa_id:  'Lebokna siswa_id kanggo ndeleng profil murid...',
    gm_kosongkan_global:      'Kosongna kanggo ndeleng statistik global',

    // ── Guru: Dashboard & Halaman ──
    gu_memuat:                'Mbukak…',
    gu_memuat_dashboard:      'Mbukak dashboard…',
    gu_sesi_berjalan:         'Sesi Presensi Lagi Mlaku',
    gu_dimulai:               'Diwiwiti',
    gu_siswa_scan:            'murid scan',
    gu_kelola_sesi:           'Kelola Sesi',
    gu_tidak_ada_sesi:        'Ora ana sesi aktif.',
    gu_mulai_sesi_baru:       '▶ Wiwiti Sesi Anyar',
    gu_early_warning_judul:   '⚠️ Early Warning',
    gu_lihat_semua:           'Deleng kabeh →',
    gu_tidak_ada_alpha:       '✅ Ora ana murid alpha dhuwur',
    gu_alpha_suffix:          '× alpha',
    gu_logbook_pending_judul: '📒 Logbook Pending',
    gu_tidak_ada_logbook_pend:'✅ Ora ana logbook pending',
    gu_kontrol_sesi:          '▶ Kontrol Sesi',
    gu_status_aktif:          'Mlaku',
    gu_status_paused:         'Dijeda',
    gu_status_selesai:        'Rampung',
    gu_total_scan:            'Total Scan',
    gu_jeda:                  '⏸ Jeda',
    gu_lanjutkan:             '▶ Lanjutake',
    gu_selesaikan:            '⏹ Rampungake',
    gu_mode_presensi:         'Mode Presensi',
    gu_mode_rombel:           'Rombel (kelas reguler)',
    gu_mode_piket:            'Piket (murid telat)',
    gu_pilih_rombel:          '-- Pilih Rombel --',
    gu_jam_label:             'Jam Pelajaran (pilih max 3 jam berurutan)',
    gu_jam_prefix:            'Jam',
    gu_memulai:               'Miwiti…',
    gu_mulai_sesi_btn:        '✅ Wiwiti Sesi',
    gu_batal:                 'Batal',
    gu_pilih_jam_error:       'Pilih paling ora 1 jam pelajaran.',
    gu_pilih_rombel_error:    'Pilih rombel dhisik.',
    gu_log_scan_judul:        '📡 Log Scan Anyar',
    gu_belum_ada_scan:        'Durung ana scan.',
    gu_col_jam_scan:          'Jam Scan',
    gu_semua_rombel:          'Kabeh Rombel',
    gu_semua_status:          'Kabeh Status',
    gu_semua:                 'Kabeh',
    gu_tidak_ada_data:        'Ora ana data.',
    gu_col_nama_siswa:        'Jeneng Murid',
    gu_col_nis:               'NIS',
    gu_periode_label:         'Periode:',
    gu_hari_suffix:           'dina',
    gu_min_alpha:             'Min Alpha:',
    gu_tidak_ada_alpha_high:  '✅ Ora ana murid alpha dhuwur.',
    gu_col_tingkat:           'Tingkat',
    gu_col_alpha:             'Alpha',
    gu_col_rate_hadir:        'Rate Rawuh',
    gu_review_label:          'Review Logbook',
    gu_catatan_placeholder:   'Katrangan (wajib yen dibalèkaké)...',
    gu_catatan_wajib:         'Katrangan kudu diisi nalika dibalèkaké.',
    gu_setujui:               '✅ Setujui',
    gu_kembalikan:            '↩ Balikaké',
    gu_col_deskripsi:         'Deskripsi',
    gu_tidak_ada_izin_pend:   '✅ Ora ana ijin pending.',
    gu_confirm_approve:       'Setujui ijin iki?',
    gu_confirm_reject:        'Tolak ijin iki?',
    gu_akun_judul:            '⚙️ Setelan Akun',
    gu_nama_label:            'Jeneng',
    gu_username_label:        'Username',
    gu_email_label:           'Email',
    gu_role_label:            'Role',
    gu_ganti_password:        'Ganti Password',
    gu_password_wajib:        'Password kudu diisi.',
    gu_password_min:          'Minimal 6 aksara.',
    gu_password_tidak_cocok:  'Konfirmasi ora cocog.',
    gu_password_baru_label:   'Password Anyar',
    gu_konfirmasi_label:      'Konfirmasi',
    gu_placeholder_password:  'Minimal 6 aksara',
    gu_placeholder_konfirmasi:'Baleni password',
    gu_menyimpan:             'Nyimpen…',
    gu_simpan_password:       '💾 Simpen Password',
    gu_password_sukses:       'Password kasil diperbarui.',

    // ── Admin: Dashboard ──
    ad_dashboard_judul:       'Dashboard Administrator',
    ad_ringkasan:             'Ringkesan sistem presensi',
    ad_memuat_dashboard:      'Mbukak data dashboard...',
    ad_gagal_memuat:          'Gagal Mbukak Dashboard',
    ad_gagal_memuat_msg:      'Gagal mbukak dashboard.',
    ad_tidak_ada_rombel:      'Ora ana data rombel.',
    ad_tidak_ada_sesi_aktif:  'Ora ana sesi aktif',
    ad_sesi_semua_selesai:    'Kabeh sesi presensi wis rampung.',
    ad_col_mode:              'Mode',
    ad_status_aktif:          'Aktif',
    ad_status_paused:         'Paused',
    ad_qa_sesi_label:         'Deleng Sesi Aktif',
    ad_qa_sesi_desc:          'Monitor sesi mlaku',
    ad_qa_users_label:        'Kelola Pengguna',
    ad_qa_users_desc:         'Tambah/edit akun',
    ad_qa_laporan_label:      'Gawe Laporan',
    ad_qa_laporan_desc:       'Export PDF/Excel',
    ad_qa_izin_label:         'Review E-Ijin',
    ad_qa_izin_desc:          'Approval ijin murid',
    ad_tren_judul:            'Tren Rawuh (14 Dina Kepungkur)',
    ad_refresh:               '↻ Refresh',
    ad_belum_ada_tren:        'Durung ana data tren.',
    ad_distribusi_status:     'Distribusi Status',
    ad_kehadiran_rombel:      'Rawuh per Rombel',
    ad_aksi_cepat:            'Aksi Cepat',
    ad_sesi_aktif_sekarang:   'Sesi Aktif Saiki',
    ad_stat_siswa_aktif:      'Total Murid Aktif',
    ad_stat_total_rombel:     'Total Rombel',
    ad_stat_sesi_aktif:       'Sesi Presensi Aktif',
    ad_stat_tingkat_hadir:    'Tingkat Rawuh',
    ad_stat_aktif_terdaftar:  'Aktif kadhaptar',
    ad_stat_kelas_aktif:      'Kelas aktif',
    ad_stat_berlangsung:      'Mlaku',
    ad_stat_tidak_ada_sesi:   'Ora ana sesi',
    ad_stat_baik:             'Becik',
    ad_stat_cukup:            'Cukup',
    ad_stat_perlu_perhatian:  'Perlu digatekake',

    // ── Admin: Sesi ──
    ad_sesi_akhiri:           'Akhiri Paksa',
    ad_memproses:             'Ngolah…',
    ad_sesi_diakhiri:         'Sesi kasil diakhiri.',
    ad_sesi_berjalan:         'Lagi Mlaku',
    ad_sesi_dijeda:           'Dijeda',
    ad_sesi_expired:          'Expired',
    ad_sesi_bermasalah:       'Masalah',
    ad_sesi_terputus:         'Pedhot',
    ad_sesi_selesai:          'Rampung',
    ad_sesi_gagal:            'Gagal',
    ad_total_sesi:            'Total Sesi',
    ad_sesi_coba_tgl_lain:    'Coba pilih tanggal liyane.',
    ad_sesi_auto_muncul:      'Data bakal muncul otomatis nalika guru mbukak sesi presensi.',
    ad_sesi_belum_ada:        'Durung ana sesi dina iki',
    ad_sesi_tidak_ada:        'Ora ana sesi ing tanggal iki',
    ad_kurang_1_mnt:          '< 1 mnt',

    // ── Admin: Early Warning ──
    ad_kritis:                'Kritis',
    ad_tinggi:                'Dhuwur',
    ad_sedang:                'Sedang',
    ad_notif_wali:            'Notifikasi Wali Kelas',
    ad_mengirim:              'Ngirim…',
    ad_notif_sukses:          'Notifikasi kasil dikirim.',
    ad_hadir_baik:            'Rawuh ing kondisi becik!',
    ad_tidak_ada_hasil:       'Ora ana asil sing cocog karo filter',
    ad_coba_ubah_filter:      'Coba owahi filter level utawa tembung kunci panggolèkan.',

    // ── Admin: Audit ──
    ad_aktivitas_hari_ini:    'Aktivitas Dina Iki',
    ad_login_hari_ini:        'Login Dina Iki',
    ad_total_log:             'Total Log',
    ad_pengguna_aktif:        'Pengguna Aktif',
    ad_pengguna_terlibat:     'Pengguna Melu',
    ad_modul_berbeda:         'Modul Beda',
    ad_sedang_online:         'Lagi Online',
    ad_hari_ini:              'Dina iki',
    ad_7_hari:                '7 dina',
    ad_30_hari:               '30 dina',
    ad_tidak_ada_data:        'Ora ana data',
    ad_mobile:                'Mobile',
    ad_tablet:                'Tablet',

    // ── Admin: Laporan ──
    ad_per_hari:              'Per Dina',
    ad_per_rombel:            'Per Rombel',
    ad_per_siswa:             'Per Murid',
    ad_col_nisn:              'NISN',
    ad_col_nama:              'Jeneng',
    ad_col_tingkatan:         'Tingkatan',
    ad_col_rate:              'Rate (%)',
    ad_col_rate_hadir:        'Rate Rawuh',
    ad_export_gagal:          'Export gagal. Coba maneh.',
    ad_bulan_ini:             'Sasi iki',
    ad_bulan_lalu:            'Sasi wingi',

    // ── Admin: Users ──
    ad_buat_pengguna:         'Gawe Pengguna',
    ad_akun_guru_sukses:      'Akun guru kasil digawe.',
    ad_akun_siswa_sukses:     'Akun murid kasil digawe.',
    ad_hapus:                 'Busak',
    ad_konfirmasi:            'Konfirmasi',
    ad_menyimpan:             'Nyimpen…',
    ad_memuat:                'Mbukak…',
    ad_password_reset_sukses: 'Password kasil direset.',
    ad_pengguna_dihapus:      'Pengguna kasil dibusak.',
    ad_pengguna_diperbarui:   'Pengguna kasil diperbarui.',
    ad_reset_password:        'Reset Password',
    ad_simpan_perubahan:      'Simpen Owahan',
    ad_online:                'Online',
    ad_idle:                  'Idle',
    ad_offline:               'Offline',
    ad_aktif:                 'Aktif',
    ad_nonaktif:              'Nonaktif',
    ad_role_admin:            'Admin',
    ad_role_guru:             'Guru',
    ad_role_siswa:            'Murid',
    ad_role_staff:            'Staff',
    ad_role_intern:           'Intern',

    // ── Admin: E-Izin ──
    ad_dispensasi:            'Dispensasi',
    ad_mengirim_izin:         'Ngirim...',
    ad_menyimpan_izin:        'Nyimpen...',
    ad_pengajuan_sukses:      'Pengajuan kasil dikirim! Ngenteni persetujuan wali kelas.',
    ad_catatan_opsional:      '(opsional)',
    ad_catatan_wajib_tolak:   '(wajib diisi nalika nolak)',

    // ── Admin: Logbook ──
    ad_belum_ada_penilaian2:  'Durung ana penilaian sing diwenehaké.',
    ad_catatan_wajib_logbook: 'Katrangan kudu diisi nalika dibalèkaké logbook.',

    // ── Admin: Analitik Prestasi & Pengaturan ──
    ad_nis_wajib:             'NIS murid kudu diisi.',
    ad_mapel_wajib:           'Mata pelajaran kudu dipilih.',
    ad_tahun_ajaran_wajib:    'Taun ajaran kudu dipilih.',
    ad_nilai_harian:          'Nilai Harian (40%)',
    ad_nilai_uts:             'Nilai UTS (30%)',
    ad_nilai_uas:             'Nilai UAS (30%)',
    ad_rata_rata_nilai:       'Rata-rata Nilai',
    ad_rate_hadir_pct:        'Rate Rawuh (%)',
    ad_nilai_akhir:           'Nilai Pungkasan',
    ad_dalam_pengembangan:    '🚧 Lagi dikembangaké',
    ad_simpan:                'Simpen',
    ad_tambah:                'Tambah',
    ad_edit:                  'Edit',
    ad_berhasil_disimpan:     'Kasil disimpen.',
    ad_berhasil_dihapus:      'Kasil dibusak.',
    ad_konfirmasi_hapus:      'Yakin mbusak iki?',
  },

  md: {
    nav_overview:  'Rengkepan',
    nav_presensi:  'Presensi',
    nav_siswa:     'Mored',
    nav_akun:      'Akun',
    nav_manajemen: 'Manajemen',
    nav_data:      'Data',
    nav_sistem:    'Sistem',
    nav_kegiatan:  'Kagiyatan',
    dashboard:           'Dasbor',
    sesi_presensi:       'Sesi Presensi',
    rekap_kehadiran:     'Rekap Hadhir',
    rekap_presensi:      'Rekap Hadhir',
    kalender_akademik:   'Almanak Akademik',
    early_warning:       'Peringatan Dini',
    logbook_pkl:         'Logbook PKL',
    e_izin:              'E-Ijin',
    pusat_komunikasi:    'Pusat Komunikasi',
    gamifikasi:          'Gamifikasi',
    pengaturan_akun:     'Pangator Akun',
    analitik_kehadiran:  'Analitik Hadhir',
    analitik_prestasi:   'Analitik Prestasi',
    logbook_praktik:     'Logbook Praktik',
    pengguna:            'Pangguna',
    laporan:             'Laporan',
    audit_trail:         'Audit Trail',
    pengaturan:          'Pangator',
    keamanan_2fa:        'Keamanan 2FA',
    keluar:       'Bhâk',
    mulai_sesi:   'Mulae Sesi',

    // ── Siswa: Ringkasan Presensi (Dashboard) ──
    sc_ringkasan_judul:   'Rengkesan Presensi',
    sc_ringkasan_sub:     "Rekap kahadhiranna be'na e sadâjâ sesi laboratorium.",
    sc_tepat_waktu:       "Teppa' Bakto",
    sc_terlambat:         'Talat',
    sc_alpha:             'Alpha',
    sc_sakit:             "Sake'",
    sc_izin:              'Edhin',
    sc_gagal_muat:        "Gagal mokka' data presensi.",
    sc_coba_lagi:         'Cobhâ Pole',

    // ── Siswa: Riwayat Presensi (Tabel) ──
    tp_judul:             'Riwayat Presensi',
    tp_subtitle:          "Rekap lengkap kahadhiranna be'na e sadâjâ sesi laboratorium.",
    tp_filter_label:      'Filter:',
    tp_filter_semua:      'Tampilaghi Kabbhi',
    tp_filter_tanggal:    'Miturut Tanggal',
    tp_tampilkan_btn:     'Tampilaghi',
    tp_tanggal_mulai:     'Tanggal molae',
    tp_tanggal_akhir:     "Tanggal dhâpenta'",
    tp_sd:                's/d',
    tp_col_no:            'No',
    tp_col_tanggal:       'Tanggal',
    tp_col_ruangan:       'Kamar',
    tp_col_kelas:         'Kelas',
    tp_col_jam_sesi:      'Jhâm Sesi',
    tp_col_selesai:       'Mare',
    tp_col_status:        'Status',
    tp_col_keterangan:    'Katerangan',
    tp_gagal_judul:       "Gagal Mokka' Data",
    tp_kosong_judul:      "Tadha' Data",
    tp_kosong_desc:       "Tadha' data presensi se cocok bân filter se epele.",
    tp_menampilkan:       'Nampilaghi',
    tp_dari:              'dâri',
    tp_data:              'data',
    tp_halaman_sebelumnya:'Alaman sabelunna',
    tp_halaman_berikutnya:'Alaman salanjuttha',
    tp_halaman:           'Alaman',

    // ── Siswa: Kalender Akademik ──
    ka_judul:             'Kalender Akademik',
    ka_subtitle:          'Jhadwal kagiyatan akademik sakola taon paneka.',
    ka_memuat:            "Mokka' kalender akademik...",
    ka_gagal_muat:        "Gagal mokka' kalender akademik.",
    ka_kosong_judul:      "Kalender Akademik Gi' Tak Badha",
    ka_kosong_desc:       "File kalender akademik gi' tak eonggha' bân admin. Ngereng hubunge pihak sakola otabâ pareksa pole dâ' ngerena.",
    ka_kosong_badge:      "Anante' onggha'an dâri admin",
    ka_perkecil:          "Kene'aghi",
    ka_perbesar:          "Raja'aghi",
    ka_reset:             'Reset',
    ka_download:          'Undhu',

    // ── Siswa: Portal E-Izin ──
    ei_judul:               'Portal E-Edhin',
    ei_subtitle:            "Ajuwagi edhin otabâ sake' ban pantau status persetujuanna",
    ei_ajukan_btn:          '+ Ajuwagi Edhin',
    ei_keterangan_wajib:    'Katerangan kodu eesse.',
    ei_sukses:              'Pengajuan edhin berhasel ekerem.',
    ei_form_judul:          "📝 Ajuwagi Edhin / Sake'",
    ei_tutup:               '✕ Totop',
    ei_jenis_label:         'Jhinis',
    ei_opt_sakit:           "🏥 Sake'",
    ei_opt_izin:            '📋 Edhin',
    ei_tgl_mulai:           'Tanggal Molae',
    ei_tgl_selesai:         'Tanggal Mare',
    ei_keterangan_label:    'Katerangan',
    ei_placeholder_alasan:  "Jhellasaghi alasan edhin/sake'...",
    ei_batal:               'Batal',
    ei_mengirim:            'Ngerem…',
    ei_kirim_btn:           '📤 Kerem Pengajuan',
    ei_riwayat_judul:       '📋 Riwayat Edhin',
    ei_refresh:             '↺ Refresh',
    ei_memuat:              "Mokka' riwayat…",
    ei_kosong:              "Gi' tak badha pengajuan edhin.",
    ei_col_status:          'Status',
    ei_col_catatan:         'Katerangan Guru',
    ei_status_menunggu_ortu:  "⏳ Anante' Reng Towa",
    ei_status_pending:        "⏳ Anante' Wali Kelas",
    ei_status_disetujui_wali: "🔄 Anante' Admin",
    ei_status_ditolak_wali:   '❌ Etolak Wali',
    ei_status_disetujui:      '✅ Esetujuwi',
    ei_status_ditolak:        '❌ Etolak',
    ei_status_menunggu:       "⏳ Anante'",

    // ── Siswa: Logbook PKL ──
    lb_status_draft:            'Draft',
    lb_status_menunggu_review:  "Anante' Review",
    lb_status_disetujui:        'Esetujuwi',
    lb_status_ditolak:          "Epabâli'",
    lb_edit_judul:              '✏️ Edit Logbook',
    lb_baru_judul:              '📝 Entri Logbook Anyar',
    lb_tutup_x:                 '✕ Totop',
    lb_tanggal_wajib:           'Tanggal kodu eesse.',
    lb_deskripsi_min:           'Deskripsi minimal 10 aksara.',
    lb_tanggal_label:           'Tanggal',
    lb_jam_mulai:                'Jhâm Molae',
    lb_jam_selesai:              'Jhâm Mare',
    lb_lokasi_label:             'Lokasi / Kennengngan PKL',
    lb_placeholder_lokasi:       'Conto: Lab Komputer Gedung A',
    lb_deskripsi_label:          'Deskripsi Kagiyatan',
    lb_placeholder_deskripsi:    "Carèta'aghi kalaban detail kagiyatan se elakone...",
    lb_foto_label:               'Path Foto Dokumentasi',
    lb_placeholder_foto:         'Conto: pkl/2026/foto-are1.jpg',
    lb_batal:                    'Batal',
    lb_simpan_draft:             '💾 Simpen Draft',
    lb_menyimpan:                'Nyempen…',
    lb_kirim_guru:               '📤 Kerem ka Guru',
    lb_judul:                    'Logbook Praktik (PKL)',
    lb_subtitle:                 'Nyatet kagiyatan saban are PKL ban kerem ka guru pembimbing kaangguy divalidasi',
    lb_tambah_btn:               '+ Tambhâ Entri',
    lb_stat_total:               'Total',
    lb_stat_menunggu:            "Anante'",
    lb_tab_daftar:                '📋 Daftar Logbook',
    lb_tab_penilaian:             '⭐ Penilaian Guru',
    lb_confirm_hapus:             'Yakin mbusak entri paneka?',
    lb_semua_status:              'Sadâjâ Status',
    lb_refresh:                   '↺ Refresh',
    lb_memuat:                    "Mokka' logbook…",
    lb_kosong:                    "Gi' tak badha entri logbook kaangguy bulân paneka.",
    lb_col_lokasi:                'Lokasi',
    lb_col_status:                'Status',
    lb_col_catatan:               'Katerangan Guru',
    lb_col_aksi:                  'Aksi',
    lb_lihat_btn:                 'Abas',
    lb_penilaian_kosong_judul:    "Gi' tak badha penilaian dâri guru pembimbing.",
    lb_penilaian_kosong_desc:     "Penilaian bakal etangale saellana guru pembimbing anilai kabbhi logbook PKL be'na.",
    lb_penilaian_akhir_dari:      "⭐ Penilaian Dhâpenta' dâri",
    lb_nilai_kedisiplinan:        'Kedisiplinan',
    lb_nilai_keterampilan:        'Katerampilan',
    lb_nilai_sikap:               'Sikap',
    lb_nilai_laporan:             'Laporan',
    lb_nilai_akhir_label:         "Nilai Dhâpenta' Logbook PKL",
    lb_catatan_dari_guru:         '💬 Katerangan dâri Guru Pembimbing:',
    lb_dinilai:                   'Eanilai:',
    lb_detail_judul:              '📋 Detail Logbook',
    lb_waktu_label:               'Bakto',
    lb_tutup_simple:              'Totop',

    // ── Shared: Pusat Komunikasi ──
    ch_baru_saja:            "Buruh gella'",
    ch_menit_lalu:           'menèt kapongkor',
    ch_jam_lalu:             'jhâm kapongkor',
    ch_hari_lalu:            'are kapongkor',
    ch_status_open:          'Open',
    ch_status_in_progress:   'Eproses',
    ch_status_waiting:       "Anante'",
    ch_status_resolved:      'Mare',
    ch_status_closed:        'Etotop',
    ch_kat_pertanyaan:       "❓ Partanya'an",
    ch_kat_keluhan:          '😤 Aroy',
    ch_kat_izin_khusus:      '📋 Edhin Khusus',
    ch_kat_konsultasi:       '💬 Konsultasi',
    ch_kat_laporan_masalah:  "🐛 Laporan Masala'",
    ch_kat_lainnya:          '📌 Laenna',
    ch_judul_min:            'Judul minimal 5 aksara.',
    ch_pesan_min:            'Pesan minimal 10 aksara.',
    ch_buat_tiket_judul:     '📩 Damel Tiket Anyar',
    ch_judul_label:          'Judul',
    ch_placeholder_judul:    "Rengkesan sèngkè' masala'/partanya'an...",
    ch_kategori_label:       'Kategori',
    ch_prioritas_label:      'Prioritas',
    ch_prio_rendah:          "🔵 Sakone'",
    ch_prio_normal:          '⚪ Normal',
    ch_prio_tinggi:          '🟡 Tenggi',
    ch_prio_urgent:          '🔴 Urgent',
    ch_pesan_deskripsi:      'Pesan / Deskripsi',
    ch_placeholder_pesan:    "Jhellasaghi partanya'an otabâ masala' sampèyan kalaban detail...",
    ch_batal:                'Batal',
    ch_mengirim:             'Ngerem…',
    ch_kirim_tiket:          '📤 Kerem Tiket',
    ch_proses_btn:           '▶ Proses',
    ch_selesaikan_btn:       '✅ Mareaghi',
    ch_tutup_tiket_btn:      'Totop Tiket',
    ch_memuat_percakapan:    "Mokka' oca'an…",
    ch_belum_ada_balasan:    "Gi' tak badha jawaban. Molae oca'an e baba paneka.",
    ch_catatan_internal_tag: '📌 Katerangan Internal',
    ch_placeholder_balasan:  "Toles jawaban...",
    ch_catatan_internal_label: 'Katerangan internal (tak katon mored)',
    ch_kirim_balasan:        '↩ Kerem',
    ch_tiket_ditutup_info:   "Tiket paneka la etotop. Damel tiket anyar mon gi' badha partanya'an.",
    ch_judul_halaman:        'Pusat Komunikasi',
    ch_subtitle_siswa:       "Kerem partanya'an, aroy, otabâ edhin khusus ka guru/admin",
    ch_subtitle_lain:        'Kelola tiket komunikasi dâri mored',
    ch_buat_tiket_short:     '+ Damel Tiket',
    ch_cari_placeholder:     "🔍 Nyareh judul tiket...",
    ch_semua_status:         'Sadâjâ Status',
    ch_semua_kategori:       'Sadâjâ Kategori',
    ch_refresh:              '↺ Refresh',
    ch_memuat_tiket:         "Mokka' tiket…",
    ch_kosong_filter:        "Tadha' tiket se cocok bân filter paneka.",
    ch_kosong_siswa:         "Gi' tak badha tiket. Klik \"+ Damel Tiket\" kaangguy molae.",
    ch_kosong_lain:          "Tadha' tiket maso' samangken.",
    ch_balasan_suffix:       'jawaban',
    ch_hapus_tiket_title:    'Busak tiket',
    ch_confirm_hapus:        'Yakin mbusak tiket paneka?',

    // ── Shared: Gamifikasi ──
    gm_tipe_hadir_tepat:      "Hadhir Teppa' Bakto",
    gm_tipe_hadir_terlambat:  'Hadhir (Talat)',
    gm_tipe_izin_surat:       'Edhin ngangguy Sorat',
    gm_tipe_streak7:          'Bonus Streak 7 Are',
    gm_tipe_streak30:         'Bonus Streak 30 Are',
    gm_tipe_perfect_month:    'Bonus Perfect Month',
    gm_tipe_submit_logbook:   'Submit Logbook',
    gm_tipe_logbook_approved: 'Logbook Esetujuwi',
    gm_tipe_tiket_selesai:    'Tiket Emareaghi',
    gm_tipe_early_bird:       'Early Bird',
    gm_tipe_bonus_admin:      'Bonus dâri Admin',
    gm_memuat_profil:         "Mokka' profil gamifikasi…",
    gm_data_kosong:           "Data tadha'.",
    gm_siswa_aktif:           'Mored Aktif',
    gm_total_poin_bulan:      'Total Poin Bulân Paneka',
    gm_badge_diraih:          "Badge Ekaollè",
    gm_top5_judul:            '🏆 Top 5 Mored Bulân Paneka',
    gm_belum_ada_poin:        "Gi' tak badha data poin. Jhalannagi kalkulasi poin gallu.",
    gm_col_siswa:             'Mored',
    gm_col_rombel:            'Rombel',
    gm_col_poin:              'Poin',
    gm_hint_cari_siswa:       "💡 Kaangguy nengale profil poin mored tertèntoh, maso'aghi siswa_id e kolom nyare e attas.",
    gm_total_poin:            'Total Poin',
    gm_poin_lagi_ke:          'poin pole ka',
    gm_poin_bulan_ini:        'Poin Bulân Paneka',
    gm_ranking_rombel:        'Ranking Rombel',
    gm_streak_hari_ini:       'Streak Are Paneka',
    gm_badge_diraih_section:  "🎖️ Badge Ekaollè",
    gm_riwayat_poin_judul:    '📋 Riwayat Poin Anyar',
    gm_belum_ada_riwayat:     "Gi' tak badha riwayat poin.",
    gm_col_aktivitas:         'Aktivitas',
    gm_global_semua_rombel:   '🌐 Global (sadâjâ rombel)',
    gm_refresh:               '↺ Refresh',
    gm_poin_suffix:           'poin',
    gm_memuat_leaderboard:    "Mokka' leaderboard…",
    gm_belum_ada_poin_periode:"Gi' tak badha data poin kaangguy periode paneka.",
    gm_col_hari_hadir:        'Are Hadhir',
    gm_kamu_suffix:           "← Be'na",
    gm_posisi_kamu:           "📍 Posisi be'na bulân paneka:",
    gm_kat_kehadiran:         '📅 Hadhir',
    gm_kat_logbook:           '📒 Logbook PKL',
    gm_kat_komunikasi:        '💬 Komunikasi',
    gm_kat_prestasi:          '🏆 Prestasi',
    gm_kat_khusus:            '⭐ Khusus',
    gm_memuat_katalog:        "Mokka' katalog badge…",
    gm_diraih_tag:            "✅ Ekaollè",
    gm_confirm_hitung_prefix: 'Etong pole poin & badge kaangguy bulân',
    gm_confirm_hitung_suffix: '? Proses paneka bakal moparoy kabbhi data poin bulân paneka.',
    gm_kalkulasi_judul:       '⚙️ Kalkulasi Poin & Badge',
    gm_kalkulasi_desc:        "Jhalannagi kalkulasi pole poin ban badge kaangguy sadâjâ mored aktif e settong bulân. Biyasana elakone e dâpenta' bulân otabâ saellana data presensi ekoreksi.",
    gm_menghitung:            '⏳ Etong…',
    gm_hitung_sekarang:       '▶ Etong Samangken',
    gm_hasil_selesai:         '✅ Mare —',
    gm_hasil_siswa_diproses:  'mored eproses ·',
    gm_hasil_poin_diberikan:  "poin eberri' ·",
    gm_hasil_badge_diraih:    'badge ekaollè',
    gm_tab_profil:            '🎮 Profil Poin',
    gm_tab_leaderboard:       '🏆 Leaderboard',
    gm_tab_katalog:           '🎖️ Katalog Badge',
    gm_judul_halaman:         'Gamifikasi Hadhir',
    gm_subtitle:              "Kompol poin, kaollè badge, ban kompetisi e leaderboard bân kancah sakelas be'na",
    gm_placeholder_siswa_id:  "Maso'aghi siswa_id kaangguy nengale profil mored...",
    gm_kosongkan_global:      'Kosongngagi kaangguy nengale statistik global',

    // ── Guru: Dashboard & Halaman ──
    gu_memuat:                "Mokka'…",
    gu_memuat_dashboard:      "Mokka' dashboard…",
    gu_sesi_berjalan:         'Sesi Presensi Satèya Jalan',
    gu_dimulai:               'Emolae',
    gu_siswa_scan:            'mored scan',
    gu_kelola_sesi:           'Kelola Sesi',
    gu_tidak_ada_sesi:        "Tadha' sesi aktif.",
    gu_mulai_sesi_baru:       '▶ Molae Sesi Anyar',
    gu_early_warning_judul:   '⚠️ Early Warning',
    gu_lihat_semua:           'Abas kabbhi →',
    gu_tidak_ada_alpha:       '✅ Tadha\' mored alpha tenggi',
    gu_alpha_suffix:          '× alpha',
    gu_logbook_pending_judul: '📒 Logbook Pending',
    gu_tidak_ada_logbook_pend:'✅ Tadha\' logbook pending',
    gu_kontrol_sesi:          '▶ Kontrol Sesi',
    gu_status_aktif:          'Jalan',
    gu_status_paused:         'Ejheda',
    gu_status_selesai:        'Mare',
    gu_total_scan:            'Total Scan',
    gu_jeda:                  '⏸ Jheda',
    gu_lanjutkan:             '▶ Laroaghi',
    gu_selesaikan:            '⏹ Mareaghi',
    gu_mode_presensi:         'Mode Presensi',
    gu_mode_rombel:           'Rombel (kelas reguler)',
    gu_mode_piket:            'Piket (mored talat)',
    gu_pilih_rombel:          '-- Pele Rombel --',
    gu_jam_label:             'Jhâm Pelajaran (pele max 3 jhâm berurutan)',
    gu_jam_prefix:            'Jhâm',
    gu_memulai:               'Molae…',
    gu_mulai_sesi_btn:        '✅ Molae Sesi',
    gu_batal:                 'Batal',
    gu_pilih_jam_error:       "Pele settong jhâm pelajaran sakone'na.",
    gu_pilih_rombel_error:    'Pele rombel galluh.',
    gu_log_scan_judul:        '📡 Log Scan Anyar',
    gu_belum_ada_scan:        "Gi' tak badha scan.",
    gu_col_jam_scan:          'Jhâm Scan',
    gu_semua_rombel:          'Sadâjâ Rombel',
    gu_semua_status:          'Sadâjâ Status',
    gu_semua:                 'Sadâjâ',
    gu_tidak_ada_data:        "Tadha' data.",
    gu_col_nama_siswa:        'Nèma Mored',
    gu_col_nis:               'NIS',
    gu_periode_label:         'Periode:',
    gu_hari_suffix:           'are',
    gu_min_alpha:             'Min Alpha:',
    gu_tidak_ada_alpha_high:  "✅ Tadha' mored alpha tenggi.",
    gu_col_tingkat:           'Tingkat',
    gu_col_alpha:             'Alpha',
    gu_col_rate_hadir:        'Rate Hadhir',
    gu_review_label:          'Review Logbook',
    gu_catatan_placeholder:   "Katerangan (kodu mon epabâli')...",
    gu_catatan_wajib:         "Katerangan kodu eesse mon epabâli'.",
    gu_setujui:               '✅ Esetujuwi',
    gu_kembalikan:            "↩ Epabâli'",
    gu_col_deskripsi:         'Deskripsi',
    gu_tidak_ada_izin_pend:   "✅ Tadha' edhin pending.",
    gu_confirm_approve:       'Esetujuwi edhin paneka?',
    gu_confirm_reject:        'Etolak edhin paneka?',
    gu_akun_judul:            '⚙️ Setelan Akun',
    gu_nama_label:            'Nèma',
    gu_username_label:        'Username',
    gu_email_label:           'Email',
    gu_role_label:            'Role',
    gu_ganti_password:        'Ganti Password',
    gu_password_wajib:        'Password kodu eesse.',
    gu_password_min:          'Minimal 6 aksara.',
    gu_password_tidak_cocok:  'Konfirmasi tak cocok.',
    gu_password_baru_label:   'Password Anyar',
    gu_konfirmasi_label:      'Konfirmasi',
    gu_placeholder_password:  'Minimal 6 aksara',
    gu_placeholder_konfirmasi:'Pole password',
    gu_menyimpan:             'Nyempen…',
    gu_simpan_password:       '💾 Simpen Password',
    gu_password_sukses:       'Password berhasel ebadhaghi.',

    // ── Admin: Dashboard ──
    ad_dashboard_judul:       'Dashboard Administrator',
    ad_ringkasan:             'Rengkesan sistem presensi',
    ad_memuat_dashboard:      "Mokka' data dashboard...",
    ad_gagal_memuat:          "Gagal Mokka' Dashboard",
    ad_gagal_memuat_msg:      "Gagal mokka' dashboard.",
    ad_tidak_ada_rombel:      "Tadha' data rombel.",
    ad_tidak_ada_sesi_aktif:  "Tadha' sesi aktif",
    ad_sesi_semua_selesai:    'Sadâjâ sesi presensi la mare.',
    ad_col_mode:              'Mode',
    ad_status_aktif:          'Aktif',
    ad_status_paused:         'Paused',
    ad_qa_sesi_label:         'Abas Sesi Aktif',
    ad_qa_sesi_desc:          'Monitor sesi jalan',
    ad_qa_users_label:        'Kelola Pengguna',
    ad_qa_users_desc:         'Tambhâ/edit akun',
    ad_qa_laporan_label:      'Damel Laporan',
    ad_qa_laporan_desc:       'Export PDF/Excel',
    ad_qa_izin_label:         'Review E-Edhin',
    ad_qa_izin_desc:          'Approval edhin mored',
    ad_tren_judul:            'Tren Hadhir (14 Are Kapongkor)',
    ad_refresh:               '↻ Refresh',
    ad_belum_ada_tren:        "Gi' tak badha data tren.",
    ad_distribusi_status:     'Distribusi Status',
    ad_kehadiran_rombel:      'Hadhir per Rombel',
    ad_aksi_cepat:            'Aksi Cepat',
    ad_sesi_aktif_sekarang:   'Sesi Aktif Samangken',
    ad_stat_siswa_aktif:      'Total Mored Aktif',
    ad_stat_total_rombel:     'Total Rombel',
    ad_stat_sesi_aktif:       'Sesi Presensi Aktif',
    ad_stat_tingkat_hadir:    'Tingkat Hadhir',
    ad_stat_aktif_terdaftar:  'Aktif edhapta',
    ad_stat_kelas_aktif:      'Kelas aktif',
    ad_stat_berlangsung:      'Jalan',
    ad_stat_tidak_ada_sesi:   "Tadha' sesi",
    ad_stat_baik:             'Sae',
    ad_stat_cukup:            'Cokop',
    ad_stat_perlu_perhatian:  'Perlu aperattèyan',

    // ── Admin: Sesi ──
    ad_sesi_akhiri:           'Phaksa Akhiri',
    ad_memproses:             'Ngeproses…',
    ad_sesi_diakhiri:         'Sesi berhasel eakhiri.',
    ad_sesi_berjalan:         'Satèya Jalan',
    ad_sesi_dijeda:           'Ejheda',
    ad_sesi_expired:          'Expired',
    ad_sesi_bermasalah:       "Badha Masala'",
    ad_sesi_terputus:         'Epotong',
    ad_sesi_selesai:          'Mare',
    ad_sesi_gagal:            'Gagal',
    ad_total_sesi:            'Total Sesi',
    ad_sesi_coba_tgl_lain:    "Cobhâ pele tanggal laen.",
    ad_sesi_auto_muncul:      'Data bakal muncol otomatis sabellunna guru mbukak sesi presensi.',
    ad_sesi_belum_ada:        "Gi' tak badha sesi are paneka",
    ad_sesi_tidak_ada:        "Tadha' sesi e tanggal paneka",
    ad_kurang_1_mnt:          '< 1 mnt',

    // ── Admin: Early Warning ──
    ad_kritis:                'Kritis',
    ad_tinggi:                'Tenggi',
    ad_sedang:                'Sedeng',
    ad_notif_wali:            'Notifikasi Wali Kelas',
    ad_mengirim:              'Ngerem…',
    ad_notif_sukses:          'Notifikasi berhasel ekerem.',
    ad_hadir_baik:            'Hadhir e kondisi sae!',
    ad_tidak_ada_hasil:       "Tadha' hasil se cocok bân filter",
    ad_coba_ubah_filter:      "Cobhâ obhâ filter level otabâ kata kunci pencarian.",

    // ── Admin: Audit ──
    ad_aktivitas_hari_ini:    'Aktivitas Are Paneka',
    ad_login_hari_ini:        'Login Are Paneka',
    ad_total_log:             'Total Log',
    ad_pengguna_aktif:        'Pengguna Aktif',
    ad_pengguna_terlibat:     'Pengguna Mèle',
    ad_modul_berbeda:         'Modul Laèn',
    ad_sedang_online:         'Satèya Online',
    ad_hari_ini:              'Are paneka',
    ad_7_hari:                '7 are',
    ad_30_hari:               '30 are',
    ad_tidak_ada_data:        "Tadha' data",
    ad_mobile:                'Mobile',
    ad_tablet:                'Tablet',

    // ── Admin: Laporan ──
    ad_per_hari:              'Per Are',
    ad_per_rombel:            'Per Rombel',
    ad_per_siswa:             'Per Mored',
    ad_col_nisn:              'NISN',
    ad_col_nama:              'Nèma',
    ad_col_tingkatan:         'Tingkatan',
    ad_col_rate:              'Rate (%)',
    ad_col_rate_hadir:        'Rate Hadhir',
    ad_export_gagal:          'Export gagal. Cobhâ pole.',
    ad_bulan_ini:             'Bulân paneka',
    ad_bulan_lalu:            'Bulân kapongkor',

    // ── Admin: Users ──
    ad_buat_pengguna:         'Damel Pengguna',
    ad_akun_guru_sukses:      'Akun guru berhasel edamel.',
    ad_akun_siswa_sukses:     'Akun mored berhasel edamel.',
    ad_hapus:                 'Busak',
    ad_konfirmasi:            'Konfirmasi',
    ad_menyimpan:             'Nyempen…',
    ad_memuat:                "Mokka'…",
    ad_password_reset_sukses: 'Password berhasel direset.',
    ad_pengguna_dihapus:      'Pengguna berhasel ebusak.',
    ad_pengguna_diperbarui:   'Pengguna berhasel ebadhaghi.',
    ad_reset_password:        'Reset Password',
    ad_simpan_perubahan:      'Simpen Obhân',
    ad_online:                'Online',
    ad_idle:                  'Idle',
    ad_offline:               'Offline',
    ad_aktif:                 'Aktif',
    ad_nonaktif:              'Nonaktif',
    ad_role_admin:            'Admin',
    ad_role_guru:             'Guru',
    ad_role_siswa:            'Mored',
    ad_role_staff:            'Staff',
    ad_role_intern:           'Intern',

    // ── Admin: E-Izin ──
    ad_dispensasi:            'Dispensasi',
    ad_mengirim_izin:         'Ngerem...',
    ad_menyimpan_izin:        'Nyempen...',
    ad_pengajuan_sukses:      "Pengajuan berhasel ekerem! Anante' persetujuan wali kelas.",
    ad_catatan_opsional:      '(opsional)',
    ad_catatan_wajib_tolak:   '(kodu eesse sèngkè\' etolak)',

    // ── Admin: Logbook ──
    ad_belum_ada_penilaian2:  "Gi' tak badha penilaian se eberri'.",
    ad_catatan_wajib_logbook: "Katerangan kodu eesse sèngkè' epabâli' logbook.",

    // ── Admin: Analitik Prestasi & Pengaturan ──
    ad_nis_wajib:             'NIS mored kodu eesse.',
    ad_mapel_wajib:           'Mata pelajaran kodu epele.',
    ad_tahun_ajaran_wajib:    'Taon ajaran kodu epele.',
    ad_nilai_harian:          'Nilai Harian (40%)',
    ad_nilai_uts:             'Nilai UTS (30%)',
    ad_nilai_uas:             'Nilai UAS (30%)',
    ad_rata_rata_nilai:       'Rata-rata Nilai',
    ad_rate_hadir_pct:        'Rate Hadhir (%)',
    ad_nilai_akhir:           "Nilai Dhâpenta'",
    ad_dalam_pengembangan:    '🚧 Satèya ependhâghi',
    ad_simpan:                'Simpen',
    ad_tambah:                'Tambhâ',
    ad_edit:                  'Edit',
    ad_berhasil_disimpan:     'Berhasel esempen.',
    ad_berhasil_dihapus:      'Berhasel ebusak.',
    ad_konfirmasi_hapus:      'Yakin mbusak paneka?',
  },
}

/** Terjemahan khusus halaman Login */
export const TLogin = {
  id: {
    brand_title:   'Sistem Presensi Lab',
    brand_sub:     'SMK Rajasa Surabaya',
    feat_iot:      'IoT Based',
    feat_secure:   'Secure',
    feat_realtime: 'Real-Time',
    welcome:       'Selamat Datang',
    welcome_sub:   'Silahkan masuk untuk mengakses sistem',
    ph_username:   'Masukkan Username',
    ph_password:   'Masukkan Password',
    remember:      'Ingat Saya',
    forgot:        'Lupa Password?',
    processing:    'Memproses...',
    login_btn:     'Login',
  },
  jw: {
    brand_title:   'Sistem Presensi Lab',
    brand_sub:     'SMK Rajasa Surabaya',
    feat_iot:      'Berbasis IoT',
    feat_secure:   'Aman',
    feat_realtime: 'Langsung',
    welcome:       'Sugeng Rawuh',
    welcome_sub:   'Mangga mlebet kanggo ngakses sistem',
    ph_username:   'Lebokaken Username',
    ph_password:   'Lebokaken Password',
    remember:      'Kèlingi Kula',
    forgot:        'Lali Password?',
    processing:    'Ngolah...',
    login_btn:     'Mlebet',
  },
  md: {
    brand_title:   'Sistem Presensi Lab',
    brand_sub:     'SMK Rajasa Surabaya',
    feat_iot:      'Adhasar IoT',
    feat_secure:   'Aman',
    feat_realtime: 'Real-Time',
    welcome:       'Salam Dhatèng',
    welcome_sub:   'Mangga mebu dâlem sistem',
    ph_username:   'Esebbhâ Username',
    ph_password:   'Esebbhâ Password',
    remember:      'Engak Kaula',
    forgot:        'Loppa Password?',
    processing:    'Moles...',
    login_btn:     'Mâsok',
  },
}
